-- CreateTable
CREATE TABLE "JSONData" (
    "id" SERIAL NOT NULL,
    "data" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "JSONData_pkey" PRIMARY KEY ("id")
);
