import "./Popup.css";
import { store } from '../../../../../Store/bookStore';

const PopupComponent = () => {
    const { icon } = store(state => state);

    return (
        icon.activeIcon !== "N/A" && (
            <div className="iconPopup">
                <div className="popupText">
                    <h1><strong>{icon.activeIcon}</strong></h1>
                    {/* Conditional rendering */}
                    {icon.activeIcon === "Smoking Area" && <p>The smoking area is a designated outdoor space where individuals can enjoy a cigarette or cigar in a relaxed environment. Often located away from non-smoking zones, it ensures that smokers have a space to unwind without disturbing others. These areas are typically equipped with seating and waste disposal bins for cigarette butts, keeping the surroundings clean. In some places, smoking areas are marked with clear signage to indicate where smoking is permitted. These zones provide a safe and controlled environment for smokers to gather, enjoy their break, and respect the preferences of non-smokers in public spaces.</p>}
                    {icon.activeIcon === "Volleyball Court" && <p>The volleyball court is a dynamic and exciting space where players come together to enjoy a competitive game or casual match. Typically surrounded by clear boundaries, the court is divided by a net, with each team striving to score points by sending the ball over the net and into the opponent's side. The court is usually made of sand in beach volleyball or hard court in indoor settings. Whether it's a professional match or a friendly game, the volleyball court encourages teamwork, agility, and sportsmanship, providing a fun and engaging environment for players of all skill levels.</p>}
                    {icon.activeIcon === "Buildings" && <p>The principal building of a university is the heart of the campus, housing administrative offices, faculty departments, and essential services for students and staff. This iconic structure often serves as the first point of contact for visitors and prospective students. Inside, you'll typically find the offices of key university leaders, including the president or chancellor, along with meeting rooms, lecture halls, and sometimes exhibition spaces. The building’s design often combines functionality with aesthetic appeal, reflecting the institution’s history, values, and commitment to academic excellence.</p>}
                    {icon.activeIcon === "Restrooms" && <p>Restrooms are essential facilities designed for personal hygiene and comfort. They are equipped with necessary amenities such as toilets, sinks, mirrors, and soap dispensers. In public places, restrooms are typically separated by gender, while some modern spaces offer gender-neutral options. These facilities are maintained to ensure cleanliness and sanitation, providing a private and hygienic environment for users. Restrooms often include additional features such as paper towel dispensers or hand dryers, and in some places, baby-changing stations or accessible stalls for individuals with disabilities.</p>}
                    {icon.activeIcon === "Labs" && <p>Labs are specialized spaces designed for conducting experiments, research, and practical work in various fields such as science, technology, and engineering. These areas are equipped with specialized equipment, analysis, and observation. Labs are commonly found research facilities.Whether it's a chemistry lab with test tubes and beakers, a computer lab with high-tech machines, or a biology lab with microscopes, these environments foster hands-on learning and discovery, helping students, researchers, and professionals explore and solve real-world problems.</p>}
                    {icon.activeIcon === "Cafeteria" && <p>The cafeteria is a bustling space where people gather to enjoy meals, snacks, and beverages in a casual, communal setting. Often found in schools, offices, hospitals, or public institutions, cafeterias offer a variety of food options to cater to different tastes and dietary needs. They provide a relaxed environment where individuals can take a break, socialize, or refuel during the day. With self-serve counters or menu options, cafeterias aim to offer convenience, affordability, and comfort. The layout typically includes seating areas for groups or individuals, making it a welcoming spot for both quick bites or leisurely meals.</p>}
                    {icon.activeIcon === "Library" && <p>The library is a quiet, resource-rich space dedicated to learning, research, and reading. It houses a vast collection of books, journals, and digital materials, providing students, faculty, and the public with access to knowledge and information. Libraries often offer study areas, computer stations, and sometimes multimedia rooms, supporting various learning methods. Many libraries host events like book clubs, lectures, and workshops. With its peaceful environment and abundant resources, the library serves as a cornerstone of academic life, promoting a culture of reading, research, and lifelong learning.</p>}
                    {icon.activeIcon === "Parking Spots" && <p>Parking spots for a university are designated areas on or near campus where students, faculty, staff, and visitors can park their vehicles. These spaces are typically divided into sections, with some reserved for specific groups such as faculty members, students, or guests. Some campuses offer permit-based parking. To improve convenience, universities may also include accessible parking spots for individuals with disabilities. Well-planned parking areas help reduce traffic congestion and ensure that everyone has access to the campus without excessive delays.</p>}
                </div>
                <img src={`/pageImages/${icon.activeIcon}.jpg`} alt="N/A" />
            </div>
        )
    );
};


export default PopupComponent;
